export default {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  DO_ASYNC: 'DO_ASYNC',
  EDIT_TODO: 'EDIT_TODO',
  FETCH_TODOS: 'FETCH_TODOS',
  MARK_TODO_AS_COMPLETED: 'MARK_TODO_AS_COMPLETED',
};
