export default {
  ADD_TODO: 'ADD_TODO',
  CLOSE_ADD_MODAL_AND_CLEAR_DATA: 'CLOSE_ADD_MODAL_AND_CLEAR_DATA',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  HIDE_BLOCK_LOADER: 'HIDE_BLOCK_LOADER',
  INIT: 'INIT',
  MARK_TODO_AS_COMPLETED: 'MARK_TODO_AS_COMPLETED',
  SET_MODAL_DATA: 'SET_MODAL_DATA',
  SHOW_ADD_MODAL: 'SHOW_ADD_MODAL',
  SHOW_BLOCK_LOADER: 'SHOW_BLOCK_LOADER',
};
